# Generated by Django 5.0.4 on 2024-08-25 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 9, 57, 16, 373536)),
        ),
    ]
