# Generated by Django 5.0.4 on 2024-08-25 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_files_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 9, 58, 5, 976635)),
        ),
    ]
