# Generated by Django 5.0.4 on 2024-08-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_files_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
