# Generated by Django 5.0.4 on 2024-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_files_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='styles',
            field=models.JSONField(default={'fontSize': 22, 'fontStyle': 'initial', 'fontWeight': 'initial', 'textDecorationLine': 'initial'}),
        ),
    ]
